name: Terraform CI

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          



      - name: Terraform Format Check
        run: terraform fmt 

      - name: Terraform Validate
        run: terraform validate
